#!/usr/bin/env bash
# Build a real Grav install from this repo and serve it.
#
# WHY THIS EXISTS: the theme cannot be previewed from the repo. Grav's system/
# and vendor/ are 60+ MB of Grav's own code and are deliberately not committed
# (see CLAUDE.md), so `python3 -m http.server` in the repo root serves the STATIC
# site — one page, frozen, retired at the cutover. Looking at that and expecting
# the eight-page site is the confusion this script removes.
#
# The install goes in .grav-dev/ INSIDE the repo, which needs justifying, because
# the repo root is the web root for the static site and a Grav core sitting there
# would be 10 MB of someone else's PHP at a public URL. Two things stop that: it
# is gitignored, and the static deploy builds its upload set from `git ls-files`,
# which cannot list an ignored path. Outside the repo would be safer still and
# was the first attempt — the editor's preview sandbox cannot reach the parent
# directory, so it could not serve it.
#
# Usage:  .github/scripts/grav-dev.sh          sync only, then use the preview
#         .github/scripts/grav-dev.sh 8790     sync and serve on that port
#
# Re-run it after editing the theme or the pages; it re-copies everything.
set -euo pipefail

PORT=${1:-}
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
G="$REPO/.grav-dev"

cd "$REPO"

if [ ! -f "$G/system/defines.php" ]; then
  echo "No Grav core at $G — downloading (once)."
  mkdir -p "$G"
  tmp=$(mktemp -d)
  curl -sS -L --max-time 300 -o "$tmp/grav.zip" https://getgrav.org/download/core/grav/latest
  unzip -q "$tmp/grav.zip" -d "$tmp"
  cp -R "$tmp/grav/." "$G/"
  rm -rf "$tmp"
  echo "Grav $(sed -n 's/.*GRAV_VERSION", "\([^"]*\)".*/\1/p' "$G/system/defines.php") installed."
fi

# Our files, replacing whatever was there. Only these three trees are ours.
rm -rf "$G/user/themes/coffeeshtob" "$G/user/pages"
mkdir -p "$G/user/themes" "$G/user/pages" "$G/user/config"
cp -R grav/user/themes/coffeeshtob "$G/user/themes/coffeeshtob"
cp -R grav/user/pages/. "$G/user/pages/"

# Photos are page media: each one goes in the folder that names it, exactly as
# the deploy does it. Same script the workflow uses.
python3 .github/scripts/page-media.py | while IFS=$'\t' read -r page file; do
  [ -n "$page" ] && cp "images/uploads/$file" "$G/user/pages/$page/$file"
done

# The web-root files, minus .htaccess: the real one forces HTTPS and this is a
# plain-http local server, so deploying it here would redirect every request to
# a URL nothing is listening on.
for f in grav/root/*; do
  [ "$(basename "$f")" = ".htaccess" ] || cp -R "$f" "$G/$(basename "$f")"
done

cat > "$G/user/config/system.yaml" <<'YAML'
# Local preview only — not deployed. Caching is off so an edit shows on reload;
# on the real site `pages.expires: 0` matters for a different reason (Grav
# otherwise tells browsers to cache the HTML for a week, which looks exactly
# like "saving is broken" to the client).
pages:
  theme: coffeeshtob
  expires: 0
cache:
  enabled: false
twig:
  cache: false
  debug: true
  auto_reload: true
errors:
  display: 1
YAML

# Grav's own router.php does `require 'index.php'` RELATIVE TO THE WORKING
# DIRECTORY, and the editor's preview runs php from the repo root, so it looked
# for index.php there and died with "Failed to open stream". This shim chdirs
# first and hands back whatever the real router returns — the router returns
# false for static files it wants the built-in server to handle, so that value
# has to propagate rather than be swallowed.
cat > "$G/dev-router.php" <<'PHP'
<?php
// Generated by .github/scripts/grav-dev.sh. Local preview only.
chdir(__DIR__);
return require __DIR__ . '/system/router.php';
PHP

rm -rf "$G/cache/twig" "$G/cache/compiled"
mkdir -p "$G/images"   # Grav requires it — it is the processed-image cache, and
                       # without it every page is a 500 saying "Essential Folders"

pages=$(find "$G/user/pages" -name '*.md' | wc -l | tr -d ' ')
if [ -z "$PORT" ]; then
  echo "Synced $pages pages into .grav-dev/ — start the preview to see them."
else
  echo "Serving $pages pages on http://localhost:$PORT"
  exec php -S "127.0.0.1:$PORT" "$G/system/router.php"
fi
